# Generated by Django 6.0.4 on 2026-04-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='No Title', max_length=100),
        ),
    ]
